travis:
  secure:
    BINSTAR_TOKEN: AklrseRCTNsCRK+m82TM9fpL00rg7Lbn0vb+j7mb0Q9PWLVe8r5f6AMUS3yfFPTjrlMrk3qqVjhNLEEVvpONzn8tIhCAElxLlCvlSdgXfVCU+rq/lo58G7nqYxB/8ntApq/ssSU8DL7JuGMd+IwiiVzynbEQi/uZksPjLLsf68cH0fZbbxOpJL5Xndzh2gyapY6wzCG/5tnPXSASz9LKfDuKvqhk0xdSolAS9YZLJR3tdciqe2MeoMYQGkivpAqDVLNjddPzw8oI/ztKr51hB/gInkbm+EajuniEoWaqslur7gcqbu7JSN0+B7qOjRRyKqTWpSmXM8iE/3gJWeJ0JQTMC5TgQ0i/vA5/H2B1Uhufxyca5lggImOpKhCAwuLWQ4xxz7jv6lUuNYfr0Z9jt16J3PUPltZBaHnDryNMc7xrKReDRNpD9AxGiHakk57I+5lWGxeRybOgpChZL4biwufJGlDXzhfa4kiytz7nn2ViqT9HOpJ+Dd5NBqkiYuKzotXmGUOITJtvTzl40Bhf9zgg7lmWIltjx88P3NMw6qf46QAe+yIT1cpM4lUdHdEejsjqfJtclLYGXjhgMt3q0JoZIyfKv2ergGyRylndKnnLhMxpDLJ87tJtk6kiSj0UQXhxJO7O/PuL3O1gzohe4xtdK5+d6xaBXtJtASb4KZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
